[package]
name = "touying-dids"
version = "0.2.0"
entrypoint = "lib.typ"
authors = ["Zixiao Huang <huangzixiaopaz@nudt.edu.cn>"]
license = "MIT"
description = "Touying Slide Theme for DIDS Lab"
homepage = "https://github.com/Coekjan/touying-buaa"
repository = "https://github.com/Coekjan/touying-buaa"
keywords = ["touying", "slide", "theme", "buaa", "beihang"]
categories = ["presentation"]
exclude = [".github/", "examples/"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.webp"
